

#ifndef _OPCODE_H_
#define _OPCODE_H_

#include "config.h"
#include "thread.h"

#include <cstdint>

UJVM_NAMESPACE_BEGIN

/*
const uint8_t opcode_nop            = (0x00);
const uint8_t opcode_aconst_null    = (0x01);
const uint8_t opcode_iconst_m1      = (0x02);
const uint8_t opcode_iconst_0       = (0x03);
const uint8_t opcode_iconst_1       = (0x04);
const uint8_t opcode_iconst_2       = (0x05);
const uint8_t opcode_iconst_3       = (0x06);
const uint8_t opcode_iconst_4       = (0x07);
const uint8_t opcode_iconst_5       = (0x08);
const uint8_t opcode_lconst_0       = (0x09);
const uint8_t opcode_lconst_1       = (0x0a);
const uint8_t opcode_fconst_0       = (0x0b);
const uint8_t opcode_fconst_1       = (0x0c);
const uint8_t opcode_fconst_2       = (0x0d);
const uint8_t opcode_dconst_0       = (0x0e);
const uint8_t opcode_dconst_1       = (0x0f);
const uint8_t opcode_bipush         = (0x10);
const uint8_t opcode_sipush         = (0x11);
const uint8_t opcode_ldc            = (0x12);
const uint8_t opcode_ldc_w          = (0x13);
const uint8_t opcode_ldc2_w         = (0x14);
const uint8_t opcode_iload          = (0x15);
const uint8_t opcode_lload          = (0x16);
const uint8_t opcode_fload          = (0x17);
const uint8_t opcode_dload          = (0x18);
const uint8_t opcode_aload          = (0x19);
const uint8_t opcode_iload_0        = (0x1a);
const uint8_t opcode_iload_1        = (0x1b);
const uint8_t opcode_iload_2        = (0x1c);
const uint8_t opcode_iload_3        = (0x1d);
const uint8_t opcode_lload_0        = (0x1e);
const uint8_t opcode_lload_1        = (0x1f);
const uint8_t opcode_lload_2        = (0x20);
const uint8_t opcode_lload_3        = (0x21);
const uint8_t opcode_fload_0        = (0x22);
const uint8_t opcode_fload_1        = (0x23);
const uint8_t opcode_fload_2        = (0x24);
const uint8_t opcode_fload_3        = (0x25);
const uint8_t opcode_dload_0        = (0x26);
const uint8_t opcode_dload_1        = (0x27);
const uint8_t opcode_dload_2        = (0x28);
const uint8_t opcode_dload_3        = (0x29);
const uint8_t opcode_aload_0        = (0x2a);
const uint8_t opcode_aload_1        = (0x2b);
const uint8_t opcode_aload_2        = (0x2c);
const uint8_t opcode_aload_3        = (0x2d);
const uint8_t opcode_iaload         = (0x2e);
const uint8_t opcode_laload         = (0x2f);
const uint8_t opcode_faload         = (0x30);
const uint8_t opcode_daload         = (0x31);
const uint8_t opcode_aaload         = (0x32);
const uint8_t opcode_baload         = (0x33);
const uint8_t opcode_caload         = (0x34);
const uint8_t opcode_saload         = (0x35);
const uint8_t opcode_istore         = (0x36);
const uint8_t opcode_lstore         = (0x37);
const uint8_t opcode_fstore         = (0x38);
const uint8_t opcode_dstore         = (0x39);
const uint8_t opcode_astore         = (0x3a);
const uint8_t opcode_istore_0       = (0x3b);
const uint8_t opcode_istore_1       = (0x3c);
const uint8_t opcode_istore_2       = (0x3d);
const uint8_t opcode_istore_3       = (0x3e);
const uint8_t opcode_lstore_0       = (0x3f);
const uint8_t opcode_lstore_1       = (0x40);
const uint8_t opcode_lstore_2       = (0x41);
const uint8_t opcode_lstore_3       = (0x42);
const uint8_t opcode_fstore_0       = (0x43);
const uint8_t opcode_fstore_1       = (0x44);
const uint8_t opcode_fstore_2       = (0x45);
const uint8_t opcode_fstore_3       = (0x46);
const uint8_t opcode_dstore_0       = (0x47);
const uint8_t opcode_dstore_1       = (0x48);
const uint8_t opcode_dstore_2       = (0x49);
const uint8_t opcode_dstore_3       = (0x4a);
const uint8_t opcode_astore_0       = (0x4b);
const uint8_t opcode_astore_1       = (0x4c);
const uint8_t opcode_astore_2       = (0x4d);
const uint8_t opcode_astore_3       = (0x4e);
const uint8_t opcode_iastore        = (0x4f);
const uint8_t opcode_lastore        = (0x50);
const uint8_t opcode_fastore        = (0x51);
const uint8_t opcode_dastore        = (0x52);
const uint8_t opcode_aastore        = (0x53);
const uint8_t opcode_bastore        = (0x54);
const uint8_t opcode_castore        = (0x55);
const uint8_t opcode_sastore        = (0x56);
const uint8_t opcode_pop            = (0x57);
const uint8_t opcode_pop2           = (0x58);
const uint8_t opcode_dup            = (0x59);
const uint8_t opcode_dup_x1         = (0x5a);
const uint8_t opcode_dup_x2         = (0x5b);
const uint8_t opcode_dup2           = (0x5c);
const uint8_t opcode_dup2_x1        = (0x5d);
const uint8_t opcode_dup2_x2        = (0x5e);
const uint8_t opcode_swap           = (0x5f);
const uint8_t opcode_iadd           = (0x60);
const uint8_t opcode_ladd           = (0x61);
const uint8_t opcode_fadd           = (0x62);
const uint8_t opcode_dadd           = (0x63);
const uint8_t opcode_isub           = (0x64);
const uint8_t opcode_lsub           = (0x65);
const uint8_t opcode_fsub           = (0x66);
const uint8_t opcode_dsub           = (0x67);
const uint8_t opcode_imul           = (0x68);
const uint8_t opcode_lmul           = (0x69);
const uint8_t opcode_fmul           = (0x6a);
const uint8_t opcode_dmul           = (0x6b);
const uint8_t opcode_idiv           = (0x6c);
const uint8_t opcode_ldiv           = (0x6d);
const uint8_t opcode_fdiv           = (0x6e);
const uint8_t opcode_ddiv           = (0x6f);
const uint8_t opcode_irem           = (0x70);
const uint8_t opcode_lrem           = (0x71);
const uint8_t opcode_frem           = (0x72);
const uint8_t opcode_drem           = (0x73);
const uint8_t opcode_ineg           = (0x74);
const uint8_t opcode_lneg           = (0x75);
const uint8_t opcode_fneg           = (0x76);
const uint8_t opcode_dneg           = (0x77);
const uint8_t opcode_ishl           = (0x78);
const uint8_t opcode_lshl           = (0x79);
const uint8_t opcode_ishr           = (0x7a);
const uint8_t opcode_lshr           = (0x7b);
const uint8_t opcode_iushr          = (0x7c);
const uint8_t opcode_lushr          = (0x7d);
const uint8_t opcode_iand           = (0x7e);
const uint8_t opcode_land           = (0x7f);
const uint8_t opcode_ior            = (0x80);
const uint8_t opcode_lor            = (0x81);
const uint8_t opcode_ixor           = (0x82);
const uint8_t opcode_lxor           = (0x83);
const uint8_t opcode_iinc           = (0x84);
const uint8_t opcode_i2l            = (0x85);
const uint8_t opcode_i2f            = (0x86);
const uint8_t opcode_i2d            = (0x87);
const uint8_t opcode_l2i            = (0x88);
const uint8_t opcode_l2f            = (0x89);
const uint8_t opcode_l2d            = (0x8a);
const uint8_t opcode_f2i            = (0x8b);
const uint8_t opcode_f2l            = (0x8c);
const uint8_t opcode_f2d            = (0x8d);
const uint8_t opcode_d2i            = (0x8e);
const uint8_t opcode_d2l            = (0x8f);
const uint8_t opcode_d2f            = (0x90);
const uint8_t opcode_i2b            = (0x91);
const uint8_t opcode_i2c            = (0x92);
const uint8_t opcode_i2s            = (0x93);
const uint8_t opcode_lcmp           = (0x94);
const uint8_t opcode_fcmpl          = (0x95);
const uint8_t opcode_fcmpg          = (0x96);
const uint8_t opcode_dcmpl          = (0x97);
const uint8_t opcode_dcmpg          = (0x98);
const uint8_t opcode_ifeq           = (0x99);
const uint8_t opcode_ifne           = (0x9a);
const uint8_t opcode_iflt           = (0x9b);
const uint8_t opcode_ifge           = (0x9c);
const uint8_t opcode_ifgt           = (0x9d);
const uint8_t opcode_ifle           = (0x9e);
const uint8_t opcode_if_icmpeq      = (0x9f);
const uint8_t opcode_if_icmpne      = (0xa0);
const uint8_t opcode_if_icmplt      = (0xa1);
const uint8_t opcode_if_icmpge      = (0xa2);
const uint8_t opcode_if_icmpgt      = (0xa3);
const uint8_t opcode_if_icmple      = (0xa4);
const uint8_t opcode_if_acmpeq      = (0xa5);
const uint8_t opcode_if_acmpne      = (0xa6);
const uint8_t opcode_goto           = (0xa7);
const uint8_t opcode_jsr            = (0xa8);
const uint8_t opcode_ret            = (0xa9);
const uint8_t opcode_tableswitch    = (0xaa);
const uint8_t opcode_lookupswitch   = (0xab);
const uint8_t opcode_ireturn        = (0xac);
const uint8_t opcode_lreturn        = (0xad);
const uint8_t opcode_freturn        = (0xae);
const uint8_t opcode_dreturn        = (0xaf);
const uint8_t opcode_areturn        = (0xb0);
const uint8_t opcode_return         = (0xb1);
const uint8_t opcode_getstatic      = (0xb2);
const uint8_t opcode_putstatic      = (0xb3);
const uint8_t opcode_getfield       = (0xb4);
const uint8_t opcode_putfield       = (0xb5);
const uint8_t opcode_invokevirtual  = (0xb6);
const uint8_t opcode_invokespecial  = (0xb7);
const uint8_t opcode_invokestatic   = (0xb8);
const uint8_t opcode_invokeinterface= (0xb9);
const uint8_t opcode_invokedynamic  = (0xba);
const uint8_t opcode_new            = (0xbb);
const uint8_t opcode_newarray       = (0xbc);
const uint8_t opcode_anewarray      = (0xbd);
const uint8_t opcode_arraylength    = (0xbe);
const uint8_t opcode_athrow         = (0xbf);
const uint8_t opcode_checkcast      = (0xc0);
const uint8_t opcode_instanceof     = (0xc1);
const uint8_t opcode_monitorenter   = (0xc2);
const uint8_t opcode_monitorexit    = (0xc3);
const uint8_t opcode_wide           = (0xc4);
const uint8_t opcode_multianewarray = (0xc5);
const uint8_t opcode_ifnull         = (0xc6);
const uint8_t opcode_ifnonnull      = (0xc7);
const uint8_t opcode_goto_w         = (0xc8);
const uint8_t opcode_jsr_w          = (0xc9);
const uint8_t opcode_breakpoint     = (0xca);
const uint8_t opcode_impdep1        = (0xfe);
const uint8_t opcode_impdep2        = (0xff);
*/

enum opcode_t {
    opcode_nop = (0x00),
    opcode_aconst_null = (0x01),
    opcode_iconst_m1 = (0x02),
    opcode_iconst_0 = (0x03),
    opcode_iconst_1 = (0x04),
    opcode_iconst_2 = (0x05),
    opcode_iconst_3 = (0x06),
    opcode_iconst_4 = (0x07),
    opcode_iconst_5 = (0x08),
    opcode_lconst_0 = (0x09),
    opcode_lconst_1 = (0x0a),
    opcode_fconst_0 = (0x0b),
    opcode_fconst_1 = (0x0c),
    opcode_fconst_2 = (0x0d),
    opcode_dconst_0 = (0x0e),
    opcode_dconst_1 = (0x0f),
    opcode_bipush = (0x10),
    opcode_sipush = (0x11),
    opcode_ldc = (0x12),
    opcode_ldc_w = (0x13),
    opcode_ldc2_w = (0x14),
    opcode_iload = (0x15),
    opcode_lload = (0x16),
    opcode_fload = (0x17),
    opcode_dload = (0x18),
    opcode_aload = (0x19),
    opcode_iload_0 = (0x1a),
    opcode_iload_1 = (0x1b),
    opcode_iload_2 = (0x1c),
    opcode_iload_3 = (0x1d),
    opcode_lload_0 = (0x1e),
    opcode_lload_1 = (0x1f),
    opcode_lload_2 = (0x20),
    opcode_lload_3 = (0x21),
    opcode_fload_0 = (0x22),
    opcode_fload_1 = (0x23),
    opcode_fload_2 = (0x24),
    opcode_fload_3 = (0x25),
    opcode_dload_0 = (0x26),
    opcode_dload_1 = (0x27),
    opcode_dload_2 = (0x28),
    opcode_dload_3 = (0x29),
    opcode_aload_0 = (0x2a),
    opcode_aload_1 = (0x2b),
    opcode_aload_2 = (0x2c),
    opcode_aload_3 = (0x2d),
    opcode_iaload = (0x2e),
    opcode_laload = (0x2f),
    opcode_faload = (0x30),
    opcode_daload = (0x31),
    opcode_aaload = (0x32),
    opcode_baload = (0x33),
    opcode_caload = (0x34),
    opcode_saload = (0x35),
    opcode_istore = (0x36),
    opcode_lstore = (0x37),
    opcode_fstore = (0x38),
    opcode_dstore = (0x39),
    opcode_astore = (0x3a),
    opcode_istore_0 = (0x3b),
    opcode_istore_1 = (0x3c),
    opcode_istore_2 = (0x3d),
    opcode_istore_3 = (0x3e),
    opcode_lstore_0 = (0x3f),
    opcode_lstore_1 = (0x40),
    opcode_lstore_2 = (0x41),
    opcode_lstore_3 = (0x42),
    opcode_fstore_0 = (0x43),
    opcode_fstore_1 = (0x44),
    opcode_fstore_2 = (0x45),
    opcode_fstore_3 = (0x46),
    opcode_dstore_0 = (0x47),
    opcode_dstore_1 = (0x48),
    opcode_dstore_2 = (0x49),
    opcode_dstore_3 = (0x4a),
    opcode_astore_0 = (0x4b),
    opcode_astore_1 = (0x4c),
    opcode_astore_2 = (0x4d),
    opcode_astore_3 = (0x4e),
    opcode_iastore = (0x4f),
    opcode_lastore = (0x50),
    opcode_fastore = (0x51),
    opcode_dastore = (0x52),
    opcode_aastore = (0x53),
    opcode_bastore = (0x54),
    opcode_castore = (0x55),
    opcode_sastore = (0x56),
    opcode_pop = (0x57),
    opcode_pop2 = (0x58),
    opcode_dup = (0x59),
    opcode_dup_x1 = (0x5a),
    opcode_dup_x2 = (0x5b),
    opcode_dup2 = (0x5c),
    opcode_dup2_x1 = (0x5d),
    opcode_dup2_x2 = (0x5e),
    opcode_swap = (0x5f),
    opcode_iadd = (0x60),
    opcode_ladd = (0x61),
    opcode_fadd = (0x62),
    opcode_dadd = (0x63),
    opcode_isub = (0x64),
    opcode_lsub = (0x65),
    opcode_fsub = (0x66),
    opcode_dsub = (0x67),
    opcode_imul = (0x68),
    opcode_lmul = (0x69),
    opcode_fmul = (0x6a),
    opcode_dmul = (0x6b),
    opcode_idiv = (0x6c),
    opcode_ldiv = (0x6d),
    opcode_fdiv = (0x6e),
    opcode_ddiv = (0x6f),
    opcode_irem = (0x70),
    opcode_lrem = (0x71),
    opcode_frem = (0x72),
    opcode_drem = (0x73),
    opcode_ineg = (0x74),
    opcode_lneg = (0x75),
    opcode_fneg = (0x76),
    opcode_dneg = (0x77),
    opcode_ishl = (0x78),
    opcode_lshl = (0x79),
    opcode_ishr = (0x7a),
    opcode_lshr = (0x7b),
    opcode_iushr = (0x7c),
    opcode_lushr = (0x7d),
    opcode_iand = (0x7e),
    opcode_land = (0x7f),
    opcode_ior = (0x80),
    opcode_lor = (0x81),
    opcode_ixor = (0x82),
    opcode_lxor = (0x83),
    opcode_iinc = (0x84),
    opcode_i2l = (0x85),
    opcode_i2f = (0x86),
    opcode_i2d = (0x87),
    opcode_l2i = (0x88),
    opcode_l2f = (0x89),
    opcode_l2d = (0x8a),
    opcode_f2i = (0x8b),
    opcode_f2l = (0x8c),
    opcode_f2d = (0x8d),
    opcode_d2i = (0x8e),
    opcode_d2l = (0x8f),
    opcode_d2f = (0x90),
    opcode_i2b = (0x91),
    opcode_i2c = (0x92),
    opcode_i2s = (0x93),
    opcode_lcmp = (0x94),
    opcode_fcmpl = (0x95),
    opcode_fcmpg = (0x96),
    opcode_dcmpl = (0x97),
    opcode_dcmpg = (0x98),
    opcode_ifeq = (0x99),
    opcode_ifne = (0x9a),
    opcode_iflt = (0x9b),
    opcode_ifge = (0x9c),
    opcode_ifgt = (0x9d),
    opcode_ifle = (0x9e),
    opcode_if_icmpeq = (0x9f),
    opcode_if_icmpne = (0xa0),
    opcode_if_icmplt = (0xa1),
    opcode_if_icmpge = (0xa2),
    opcode_if_icmpgt = (0xa3),
    opcode_if_icmple = (0xa4),
    opcode_if_acmpeq = (0xa5),
    opcode_if_acmpne = (0xa6),
    opcode_goto = (0xa7),
    opcode_jsr = (0xa8),
    opcode_ret = (0xa9),
    opcode_tableswitch = (0xaa),
    opcode_lookupswitch = (0xab),
    opcode_ireturn = (0xac),
    opcode_lreturn = (0xad),
    opcode_freturn = (0xae),
    opcode_dreturn = (0xaf),
    opcode_areturn = (0xb0),
    opcode_return = (0xb1),
    opcode_getstatic = (0xb2),
    opcode_putstatic = (0xb3),
    opcode_getfield = (0xb4),
    opcode_putfield = (0xb5),
    opcode_invokevirtual = (0xb6),
    opcode_invokespecial = (0xb7),
    opcode_invokestatic = (0xb8),
    opcode_invokeinterface = (0xb9),
    opcode_invokedynamic = (0xba),
    opcode_new = (0xbb),
    opcode_newarray = (0xbc),
    opcode_anewarray = (0xbd),
    opcode_arraylength = (0xbe),
    opcode_athrow = (0xbf),
    opcode_checkcast = (0xc0),
    opcode_instanceof = (0xc1),
    opcode_monitorenter = (0xc2),
    opcode_monitorexit = (0xc3),
    opcode_wide = (0xc4),
    opcode_multianewarray = (0xc5),
    opcode_ifnull = (0xc6),
    opcode_ifnonnull = (0xc7),
    opcode_goto_w = (0xc8),
    opcode_jsr_w = (0xc9),
    opcode_breakpoint = (0xca),
    opcode_impdep1 = (0xfe),
    opcode_impdep2 = (0xff),
};

UJVM_NAMESPACE_END

#endif